//This file is auto-generated by Digitizer

#ifndef _MONSTER_DEFS_H_
#define _MONSTER_DEFS_H_

#include <Arduino.h>

enum MonsterName {
Empty,
Agu2006_Digitama,
Botamon,
Koromon,
Agumon,
Elecmon,
Greymon,
Tyrannomon,
Numemon,
RandomEgg
};

enum MonsterStage {
	digitama,
    baby,
    baby_ii,
    child,
    adult,
    perfect,
    ultimate,
    armor
};

struct MonsterRef {
        String filepath;
        MonsterName name;
        MonsterStage stage;
        int lifespan;
        String move_style;
        int speed;
        String bg;
        MonsterName evos[8];
};

static const MonsterRef MonsterDB[] = {
{
	"sprites/digitama/Agu2006_Digitama.bmp",
	Empty,
	digitama,
	0,
	"walk",
	2,
	"None",
	{Empty}
},
{
	"sprites/digitama/Agu2006_Digitama.bmp",
	Agu2006_Digitama,
	digitama,
	30,
	"walk",
	0,
	"bg/bg_0.bmp",
	{Botamon}
},
{
	"sprites/baby/Botamon.bmp",
	Botamon,
	baby,
	60,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Koromon}
},
{
	"sprites/baby_ii/Koromon.bmp",
	Koromon,
	baby_ii,
	90,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Agumon, Elecmon}
},
{
	"sprites/child/Agumon.bmp",
	Agumon,
	child,
	120,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Greymon, Tyrannomon}
},
{
	"sprites/child/Elecmon.bmp",
	Elecmon,
	child,
	120,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Tyrannomon, Numemon}
},
{
	"sprites/adult/Greymon.bmp",
	Greymon,
	adult,
	120,
	"walk",
	2,
	"bg/bg_0.bmp",
	{RandomEgg}
},
{
	"sprites/adult/Tyrannomon.bmp",
	Tyrannomon,
	adult,
	120,
	"walk",
	2,
	"bg/bg_0.bmp",
	{RandomEgg}
},
{
	"sprites/adult/Numemon.bmp",
	Numemon,
	adult,
	120,
	"walk",
	2,
	"bg/bg_0.bmp",
	{RandomEgg}
},
{
	"sprites/adult/Tyrannomon.bmp",
	RandomEgg,
	adult,
	0,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Agu2006_Digitama}
}
};
#endif //_MONSTER_DEFS_H_