//This file is auto-generated by Digitizer

#ifndef _MONSTER_DEFS_H_
#define _MONSTER_DEFS_H_

#include <Arduino.h>

enum MonsterName {
Empty,
Kiimon,
Imp_Digitama,
Yaamon,
Impmon_X,
Gazimon_X,
RandomEgg
};

enum MonsterStage {
	digitama,
    baby,
    baby_ii,
    child,
    adult,
    perfect,
    ultimate,
    armor
};

struct MonsterRef {
        String filepath;
        MonsterName name;
        MonsterStage stage;
        int lifespan;
        String move_style;
        int speed;
        String bg;
        MonsterName evos[8];
};

static const MonsterRef MonsterDB[] = {
{
	"sprites/digitama/Agu2006_Digitama.bmp",
	Empty,
	digitama,
	0,
	"walk",
	2,
	"None",
	{Empty}
},
{
	"sprites/baby/Kiimon.bmp",
	Kiimon,
	baby,
	50,
	"walk",
	2,
	"bg/169_0xa9.bmp",
	{Yaamon}
},
{
	"sprites/digitama/Imp_Digitama.bmp",
	Imp_Digitama,
	digitama,
	50,
	"walk",
	0,
	"bg/169_0xa9.bmp",
	{Kiimon}
},
{
	"sprites/baby_ii/Yaamon.bmp",
	Yaamon,
	baby_ii,
	50,
	"walk",
	2,
	"bg/169_0xa9.bmp",
	{Impmon_X, Gazimon_X}
},
{
	"sprites/child/Impmon_X.bmp",
	Impmon_X,
	child,
	50,
	"walk",
	2,
	"bg/169_0xa9.bmp",
	{RandomEgg}
},
{
	"sprites/child/Gazimon_X.bmp",
	Gazimon_X,
	child,
	50,
	"walk",
	2,
	"bg/188_0xbc.bmp",
	{RandomEgg}
},
{
	"sprites/adult/Tyrannomon.bmp",
	RandomEgg,
	adult,
	0,
	"walk",
	2,
	"bg/bg_0.bmp",
	{Imp_Digitama}
}
};
#endif //_MONSTER_DEFS_H_